import React from 'react';
import { motion } from 'framer-motion';
import { Github, Linkedin, Mail, Twitter } from 'lucide-react';

export const About: React.FC = () => {
  return (
    <section className="min-h-screen pt-32 pb-20 px-6 flex items-center justify-center">
      <div className="max-w-2xl w-full">
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-surface border border-slate-800 rounded-2xl p-8 md:p-12 relative overflow-hidden"
        >
             <div className="absolute top-0 right-0 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>

            <h1 className="text-3xl font-bold text-white mb-6">About NovaTech</h1>
            
            <div className="space-y-4 text-slate-400 leading-relaxed mb-8">
                <p>
                    NovaTech is an experimental blog platform designed to push the boundaries of what a modern personal website can look like. 
                    It leverages React for a seamless single-page application experience and Tailwind CSS for rapid, atomic styling.
                </p>
                <p>
                    More importantly, the content you see here is often augmented or generated by <strong>Gemini 2.5</strong>, 
                    showcasing how Large Language Models can be integrated into production workflows to scaffold creative technical writing.
                </p>
                <p>
                    Built with TypeScript, Framer Motion, and a love for dark mode aesthetics.
                </p>
            </div>

            <div className="flex space-x-6">
                <a href="#" className="text-slate-400 hover:text-cyan-400 transition-colors"><Github className="w-6 h-6" /></a>
                <a href="#" className="text-slate-400 hover:text-cyan-400 transition-colors"><Twitter className="w-6 h-6" /></a>
                <a href="#" className="text-slate-400 hover:text-cyan-400 transition-colors"><Linkedin className="w-6 h-6" /></a>
                <a href="#" className="text-slate-400 hover:text-cyan-400 transition-colors"><Mail className="w-6 h-6" /></a>
            </div>
        </motion.div>
      </div>
    </section>
  );
};
